namespace JobPortal.Application.DTOs;

public record ApplicationStepItemDto(
    int Id,
    int JobStepId,
    string StepName,
    int StepOrder,
    bool IsRequired,
    string Status,
    DateTime? CompletedAt,
    int? CompletedByUserId,
    string? CompletedByName);

public record ApplicationDocumentDto(
    int Id,
    string DocumentType,
    string OriginalFileName,
    string FilePath,
    string FileType,
    DateTime CreatedAt,
    bool IsCompanyDocument);

public record ApplicationDto(
    int Id,
    string Code,
    int JobPostId,
    string JobPostTitle,
    string? JobPostSlug,
    string? JobPostCity,
    string? JobPostCountry,
    string? JobPostDepartmentName,
    string? JobPostEmploymentTypeName,
    string? JobPostWorkModeName,
    string? JobPostJobLevelName,
    int UserId,
    string CandidateName,
    string CandidateEmail,
    string? CandidatePhone,
    string? CandidateEducationLevelName,
    string? CandidateEducationMajorName,
    string? CandidateInstitutionName,
    int? CandidateEducationStartYear,
    int? CandidateEducationEndYear,
    DateOnly? CandidateDateOfBirth,
    string Status,
    DateTime AppliedAt,
    DateTime UpdatedAt,
    IEnumerable<ApplicationStepItemDto> Steps,
    IEnumerable<ApplicationDocumentDto> Documents,
    int? Rating,
    string? RatingNote,
    DateTime? RatedAt,
    int? DmRating,
    string? DmRatingNote,
    DateTime? DmRatedAt,
    string? Source);
